/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'github-oauth-init': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'forget-password': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'logout': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'protected-route': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'signin': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'verify-the-user': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'send-verify-email': EventHandler<never, never>
    'store-email-token': EventHandler<never, { topic: 'send-email'; data: never }>
    'store-user-db': EventHandler<never, never>
    'signup': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'store-user-db'; data: never } | { topic: 'store-email-token'; data: never }>
    'github-oauth-callback': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
}