export const ERROR_CODES = {
    PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED",
    INVALID_PROJECT_CONFIG: "INVALID_PROJECT_CONFIG",
    DEPLOYMENT_FAILED: "DEPLOYMENT_FAILED",
    GITHUB_API_ERROR: "GITHUB_API_ERROR",
    DATABASE_ERROR: "DATABASE_ERROR",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
    NETWORK_ERROR: "NETWORK_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    TIMEOUT: "TIMEOUT",
    PROJECT_ALREADY_EXISTS: "PROJECT_ALREADY_EXISTS",
    PROJECT_NOT_CONFIGURED: "PROJECT_NOT_CONFIGURED",
    PROJECT_NOT_DEPLOYED: "PROJECT_NOT_DEPLOYED",
    INTERNAL_SERVER_ERROR : "INTERNAL_SERVER_ERROR",
    INVALID_OAUTH_STATE : "INVALID_OAUTH_STATE",
    OAUTH_FAILED : "OAUTH_FAILED",
    EMAIL_REQUIRED : "EMAIL_REQUIRED",
    INVALID_PAGE_NUMBER: "INVALID_PAGE_NUMBER",
    GITHUB_NOT_LINKED : "GITHUB_NOT_LINKED",
    MISSING_REPO_DATA : "MISSING_REPO_DATA",
    ERROR_FETCHING_YT_DETAILS : "ERROR_FETCHING_YT_DETAILS",
    PIPELINE_ALREADY_EXISTS : "PIPELINE_ALREADY_EXISTS",
    PIPELINE_NOT_FOUND : "PIPELINE_NOT_FOUND"




}
